[package]
name = "cthulhu"
description = "Macro for invoking cthulhu"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"
repository = "https://github.com/killercup/cthulhu"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.5"
quote = "1.0.2"
proc-macro2 = "1.0.3"
darling = "0.10.0"
cthulhu_calling = { path = "../cthulhu_calling" }
